apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-api
spec:
  selector:
    matchLabels:
      run: calc-api
  replicas: 1
  template:
    metadata:
      labels:
        run: calc-api
    spec:
      containers:
        - name: calc-api
          image: igniteregtest.azurecr.io/calc-api
          ports:
            - containerPort: 8090
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: calc-api
  labels:
    run: calc-api
spec:
  ports:
    - port: 80
  selector:
    run: cacl-api
---
apiVersion: v1
kind: Service
metadata:
  name: calc-api-external
  labels:
    run: calc-api-external
spec:
  type: LoadBalancer
  selector:
    run: calc-api
  ports:
    - name: http
      port: 80
      targetPort: 8090
